simple_circular:
	g++ simple_circular.cpp -I/usr/include/SDL -I/usr/local/include/fifechan -lSDL -lSDL_image -lfifechan -lfifechan_sdl -lfifechan_opengl -lGL  -o simple_circular.out	

circular_remove:
	g++ circular_remove.cpp -I/usr/include/SDL -I/usr/local/include/fifechan -lSDL -lSDL_image -lfifechan -lfifechan_sdl -lfifechan_opengl -lGL  -o circular_remove.out	

clean:
	rm -rf *.out
