spacers_in_vbox_hbox:	
	g++ spacers_in_vbox_hbox.cpp -I/usr/include/SDL -I/usr/local/include/fifechan -lSDL -lSDL_image -lfifechan -lfifechan_sdl -lfifechan_opengl -lGL  -o spacers_in_vbox_hbox.out

dynamic_remove_spacers:	
	g++ dynamic_remove_spacers.cpp -I/usr/include/SDL -I/usr/local/include/fifechan -lSDL -lSDL_image -lfifechan -lfifechan_sdl -lfifechan_opengl -lGL  -o dynamic_remove_spacers.out

clean:
	rm -rf *.out
