hbox_in_vbox:	
	g++ hbox_in_vbox.cpp -I/usr/include/SDL -I/usr/local/include/fifechan -lSDL -lSDL_image -lfifechan -lfifechan_sdl -lfifechan_opengl -lGL  -o test_hbox_in_vbox.out

remove_child:	
	g++ remove_child.cpp -I/usr/include/SDL -I/usr/local/include/fifechan -lSDL -lSDL_image -lfifechan -lfifechan_sdl -lfifechan_opengl -lGL  -o remove_child.out

resize_child:
	g++ resize_child.cpp -I/usr/include/SDL -I/usr/local/include/fifechan -lSDL -lSDL_image -lfifechan -lfifechan_sdl -lfifechan_opengl -lGL  -o resize_child.out	

clean:
	rm -rf *.out
